services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --no-locale
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
      interval: 1s
      timeout: 1s
      retries: 5
    volumes:
      - ./postgres_volume:/var/lib/postgresql/data
  app:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
